name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
#  pull_request:
#    types: [opened, synchronize, reopened, closed]
#    branches:
#      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Environment
        run: env | sort

      - name: Prepare Artifact
        env:
          CI_BUILD_NUMBER: '${{ github.run_id }}.${{ github.run_number }}x${{ github.run_attempt }}'
          CI_BUILD_JOB_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        run: |
          npm pkg set buildNumber=$CI_BUILD_NUMBER
          npm pkg set buildJobUrl=$CI_BUILD_JOB_URL

          echo $CI_BUILD_JOB_URL
          echo Package.json - set buildNumber

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_HILL_05D53C20F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
#          deployment_environment: 'dev'
        env:
          STRAPI_API: "https://cms-strapi-server.azurewebsites.net"
          APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=d783744f-2519-49e0-87a5-06a1d7546edf;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/

      - name: Smoke Test
        timeout-minutes: 1
        run: $(GITHUB_WORKSPACE)/.github/workflows/scripts/smokeTest.sh

  close_pull_request_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_HILL_05D53C20F }}
          action: "close"
